"""
Nexa Agent — Planning Tools: Self-Extension (v4.1.0)
=====================================================

The "getting smarter" tier:

- :func:`create_tool`        — write a brand-new Nexa tool into the
  user-writable directory ``~/.nexa/tools/``. The tool is auto-discovered
  at the *next* registry build (``create_default_registry`` scans that
  directory). This is how Nexa extends itself on the user's machine.

- :func:`plan_and_delegate`  — a meta-tool that runs :func:`task_plan` and
  emits, for each top-level step, a ready-to-use prompt for the existing
  ``delegate`` tool. Lets the agent move from *planning* to *doing* in
  one shot.

Copyright (c) 2026 Dearly Febriano Irwansyah
SPDX-License-Identifier: MIT

(The MIT license remains with Dearly Febriano Irwansyah even for tools the
agent itself writes — see LICENSE §2.)
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

import nexa.config as _config
from tools.planning.todos import task_plan


# ---------------------------------------------------------------------------
# User-tool directory helpers
# ---------------------------------------------------------------------------
def _user_tools_dir():
    """Return the user-writable tools directory, creating it if needed.

    Reads ``NEXA_HOME`` from the config module at *call time* so tests can
    monkeypatch ``nexa.config.NEXA_HOME`` (or ``process_manager``-style
    overrides) and have them picked up here.
    """
    d = _config.NEXA_HOME / "tools"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _tool_filename(name: str) -> str:
    """Turn a tool name into a safe Python module filename."""
    safe = re.sub(r"[^A-Za-z0-9_]+", "_", name).strip("_").lower()
    if not safe:
        safe = "custom_tool"
    if safe[0].isdigit():
        safe = f"tool_{safe}"
    return f"{safe}.py"


# Template for a freshly-minted tool. The {{PLACEHOLDER}}s are filled in.
_TOOL_TEMPLATE = '''"""
Nexa Agent — User Tool: {name}
================================

Auto-generated by the ``create_tool`` meta-tool.

{description}

MIT License — (c) 2026 Dearly Febriano Irwansyah.
The user owns this file; the agent may edit it freely.
"""

from __future__ import annotations

import asyncio
from typing import Any, Dict


async def {fn_name}({args_signature}) -> str:
    """
    {docstring}
    """
    # TODO: implement the tool body. Suggested skeleton:
{body}
    return "ok"


#: OpenAI function-calling schema.
{schema_name}: Dict[str, Any] = {schema}
'''


def _default_args_signature(params: List[str]) -> str:
    """Return a Python function signature fragment for the given param names."""
    if not params:
        return ""
    parts = [f"{p}: str" for p in params]
    return ", ".join(parts)


async def create_tool(
    name: str,
    description: str,
    parameters: Optional[List[str]] = None,
    body: Optional[str] = None,
) -> str:
    """
    Draft a new Nexa tool as a Python file in ``~/.nexa/tools/``.

    The tool becomes available the *next* time the registry is built
    (i.e. the next conversation turn), because the registry's user-tool
    loader scans that directory.

    Args:
        name:        The tool name (letters, digits, ``_``). Also the
                     Python module name.
        description: Human-readable description (surfaced to the LLM).
        parameters:  List of parameter names — all become ``str`` args in
                     the generated function and the OpenAI schema.
        body:        Optional Python source for the tool body. If omitted,
                     a friendly TODO skeleton is written instead.

    Returns:
        A confirmation with the file path.
    """
    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name or ""):
        return (
            "**Error.** `name` must be a valid Python identifier "
            "(letters, digits, `_`, not starting with a digit)."
        )
    if not description.strip():
        return "**Error.** `description` cannot be empty."

    parameters = [p for p in (parameters or []) if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", p)]
    schema_name = f"{name.upper()}_SCHEMA"

    if body:
        # Normalize the user-provided body: dedent to the *minimal* existing
        # indent, then re-indent to 4 spaces (function body). This way both
        # ``return x`` and ``    return x`` produce valid code.
        lines = body.rstrip().splitlines()
        min_indent = min(
            (len(line) - len(line.lstrip()) for line in lines if line.strip()),
            default=0,
        )
        body_code = "\n".join("    " + line[min_indent:] if line.strip() else "" for line in lines)
    else:
        body_code = (
            "    # Read parameters, do something useful,\n"
            "    # and return a short Markdown report.\n"
            f"    return f\"{name}(\" + \", \".join([{', '.join(parameters) if parameters else ''}]) + \") not yet implemented\"\n"
        )

    schema = {
        "type": "object",
        "properties": {
            p: {"type": "string", "description": f"Parameter {p}."} for p in parameters
        },
        "required": list(parameters),
    }

    source = _TOOL_TEMPLATE.format(
        name=name,
        fn_name=name,
        description=description,
        docstring=description.replace('"""', '\"\"\"'),
        args_signature=_default_args_signature(parameters),
        body=body_code,
        schema_name=schema_name,
        schema=repr(schema),
    )

    path = _user_tools_dir() / _tool_filename(name)
    # Never overwrite an existing tool silently — version the filename.
    if path.exists():
        stem = path.stem
        i = 2
        while (_user_tools_dir() / f"{stem}_v{i}{path.suffix}").exists():
            i += 1
        path = _user_tools_dir() / f"{stem}_v{i}{path.suffix}"

    path.write_text(source, encoding="utf-8")

    # Try loading it to surface import-time errors early.
    load_result = ""
    try:
        import importlib.util, sys
        mod_name = f"nexa_user_{path.stem}"
        spec = importlib.util.spec_from_file_location(mod_name, path)
        if spec and spec.loader:
            mod = importlib.util.module_from_spec(spec)
            sys.modules[mod_name] = mod
            spec.loader.exec_module(mod)
            if not hasattr(mod, name) or not hasattr(mod, schema_name):
                load_result = (
                    f"\n\n⚠️ Loaded `{path.name}` but couldn't find `{name}` "
                    f"and `{schema_name}` — check the generated file."
                )
    except Exception as exc:
        load_result = f"\n\n⚠️ Tool written but import test failed: {exc}"

    return (
        f"Tool **{name}** created at `{path}`.\n\n"
        "**Available next turn.** The registry scans `~/.nexa/tools/` "
        "on every `create_default_registry()` call, so this tool will be "
        "callable the next time the agent loads its tool registry."
        + load_result
    )


CREATE_TOOL_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "name": {"type": "string", "description": "Tool name (Python identifier)."},
        "description": {"type": "string"},
        "parameters": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Parameter names.",
        },
        "body": {"type": "string", "description": "Optional Python code for the tool body."},
    },
    "required": ["name", "description"],
}


# ---------------------------------------------------------------------------
# plan_and_delegate
# ---------------------------------------------------------------------------
async def plan_and_delegate(goal: str, max_steps: int = 8) -> str:
    """
    Generate a plan AND a ready-to-use delegate prompt per step.

    Works with the existing ``delegate`` tool: take any emitted
    ``suggested_delegate_prompt`` and pass it as the ``task`` argument of
    ``delegate``.

    Args:
        goal:      The goal to plan.
        max_steps: Max number of top-level steps to expand.

    Returns:
        A Markdown document with the plan plus delegate prompts.
    """
    plan_md = await task_plan(goal, max_steps=max_steps)
    if plan_md.startswith("**Error"):
        return plan_md

    # Extract numbered steps from the plan markdown.
    steps: List[str] = []
    for line in plan_md.splitlines():
        m = re.match(r"^\d+\.\s+\[[ xX]\]\s+(.+)$", line)
        if m:
            steps.append(m.group(1).strip())

    lines = [
        plan_md,
        "",
        "---",
        "",
        "## Ready-to-use delegate prompts",
        "",
        "Use each of these with the ``delegate`` tool:",
        "",
    ]
    for i, step in enumerate(steps, 1):
        prompt = (
            f"Complete subtask {i} of the larger goal '{goal[:60]}…':\n\n"
            f"{step}\n\n"
            "Work autonomously inside the workspace, call tools as needed, "
            "and return a short summary of what you did."
        )
        lines.append(f"### Step {i}")
        lines.append("```text")
        lines.append(prompt)
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


PLAN_AND_DELEGATE_SCHEMA: Dict[str, Any] = {
    "type": "object",
    "properties": {
        "goal": {"type": "string"},
        "max_steps": {"type": "integer", "default": 8},
    },
    "required": ["goal"],
}
