"""
Skill: infrastructure_as_code
=============================

Generate infrastructure-as-code (Terraform, Pulumi, or CloudFormation) for a
cloud provider (``aws`` | ``gcp`` | ``azure`` | ``cloudflare``) from a
natural-language description. Returns the generated IaC source, a suggested
workspace file path for it, and a cost-estimate placeholder.

Permissions used:
  * ``filesystem:workspace:write`` — declared by the manifest; this handler
    does NOT write the generated code by default. The ``file_path`` field is
    a *suggested* target path string the caller may choose to materialise.
  * ``memory:read`` — declared by the manifest; this handler itself does not
    touch memory.

Honesty note: the ``iac_code`` text is generated by the model from the REAL
description supplied by the caller — nothing else writes that file and no
infrastructure is planned, applied, or validated by this skill (that would
need provider credentials and a toolchain such as ``terraform``, which are
not available here). ``estimated_cost`` is always an honest placeholder —
real numbers require a cloud pricing API that is not configured. If the
model's reply is not parseable JSON, ``ValueError`` propagates rather than
fabricating IaC.

Copyright (c) 2026 Dearly Febriano Irwansyah
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from typing import Any, Dict

from skills._common import ask_llm_json, as_list, coerce_number, coerce_str  # noqa: F401
from skills._common import require
from skills.registry import SkillInputError

__all__ = ["handle"]

_PROVIDERS = ("aws", "gcp", "azure", "cloudflare")
_IAC_TOOLS = ("terraform", "pulumi", "cloudformation")

SYSTEM = (
    "You are Nexa's infrastructure-as-code generator. You are given a REAL "
    "infrastructure description provided by the user, a cloud provider "
    "(aws | gcp | azure | cloudflare), and an IaC tool (terraform | pulumi | "
    "cloudformation). Produce syntactically plausible, self-contained source "
    "code for exactly that tool and provider that implements ONLY what the "
    "description asks for (sensible, clearly commented defaults are fine for "
    "unspecified details). Never invent resources unrelated to the request. "
    "Respond with a SINGLE JSON object, and nothing else (no markdown "
    "fences, no prose around it), with exactly these keys:\n"
    '  "iac_code": a string containing the COMPLETE source file (e.g. the '
    "full .tf / Pulumi program / CloudFormation template text). Newlines "
    "must be escaped inside the JSON string.\n"
    '  "file_path": a suggested workspace-relative path for that file, e.g. '
    '"infra/aws/main.tf".\n'
    "Do NOT include an estimated_cost key — cost estimation is handled by "
    "the caller, not you."
)


def _default_file_path(provider: str, iac_tool: str) -> str:
    """Fallback suggested path per IaC tool, if the model omits one."""
    ext = {
        "terraform": "main.tf",
        "pulumi": "__main__.py",
        "cloudformation": "template.yaml",
    }.get(iac_tool, "main.txt")
    return f"infra/{provider}/{ext}"


_COST_STUB = {"note": "estimate requires pricing API, not configured"}


def _estimated_cost_stub(raw: Any) -> Dict[str, Any]:
    """
    Honest cost placeholder. We never fabricate currency numbers and never
    surface model-claimed pricing either (a local model cannot query a cloud
    pricing API), so anything the model says about cost is dropped in favour
    of the fixed, truthful stub.
    """
    return dict(_COST_STUB)


async def handle(input_data: dict, provider) -> dict:
    """Generate IaC source for a description; returns code + suggested path."""
    description = require(input_data, "description", str, "infrastructure description")
    cloud = require(input_data, "provider", str, "cloud provider")
    iac_tool = require(input_data, "iac_tool", str, "IaC tool")
    if cloud not in _PROVIDERS:
        raise SkillInputError(
            f"provider must be one of {sorted(_PROVIDERS)}, got {cloud!r}"
        )
    if iac_tool not in _IAC_TOOLS:
        raise SkillInputError(
            f"iac_tool must be one of {sorted(_IAC_TOOLS)}, got {iac_tool!r}"
        )

    prompt = (
        f"Cloud provider: {cloud}\n"
        f"IaC tool: {iac_tool}\n\n"
        f"INFRASTRUCTURE DESCRIPTION (verbatim, supplied by the caller):\n"
        f"-----\n{description}\n-----\n\n"
        f"Generate complete {iac_tool} source code for provider {cloud} that "
        "implements ONLY the description above. Suggest a workspace-relative "
        "file path for it.\n\n"
        'Return a single JSON object with keys "iac_code" (string — the '
        'entire source file) and "file_path" (string).'
    )

    data: Dict[str, Any] = await ask_llm_json(provider, prompt, system=SYSTEM)

    # Normalise TYPES only — the code text, the path, and any cost narrative
    # always come from the model's reply about the real description.
    file_path = coerce_str(data.get("file_path")).strip() or _default_file_path(
        cloud, iac_tool
    )
    return {
        "iac_code": coerce_str(data.get("iac_code")),
        "file_path": file_path,
        "estimated_cost": _estimated_cost_stub(data.get("estimated_cost")),
    }
