"""
Skill: monitoring_setup
=======================

Generate ready-to-use monitoring configuration files (scrape config, alerting
rules, dashboard definition) for a workspace application on a chosen
observability platform (``prometheus`` | ``datadog`` | ``newrelic``), from
the caller's REAL metrics list and alerting spec.

Permissions used:
  * ``filesystem:workspace:write`` — declared by the manifest; this handler
    does NOT write the generated files by default — ``config_files`` are
    returned as ``{path, content}`` pairs for the caller to review first.
  * ``terminal:execute`` — declared by the manifest; this handler executes no
    terminal commands.

Honesty note: the ``content`` of every config file is generated by the model
from the REAL app path, metrics, and alerting values supplied by the caller —
nothing is pre-canned per platform. The configs are NOT installed anywhere
and ``dashboard_url`` is always "" (no dashboard was created — creating one
would require platform credentials, which are not available). If the model's
reply is not parseable JSON, ``ValueError`` propagates rather than
fabricating config files.

Copyright (c) 2026 Dearly Febriano Irwansyah
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from agent import tool_api
from skills._common import ask_llm_json, as_list, coerce_number, coerce_str  # noqa: F401
from skills._common import require
from skills.registry import SkillInputError

__all__ = ["handle"]

_PLATFORMS = ("prometheus", "datadog", "newrelic")

SYSTEM = (
    "You are Forge's observability-config generator. You are given the REAL "
    "directory listing of an application (read from the caller's workspace), "
    "the REAL list of metrics the caller wants tracked, their alerting "
    "specification (JSON), and a platform (prometheus | datadog | newrelic). "
    "Generate accurate, syntactically plausible config files for exactly "
    "that platform, covering exactly the requested metrics and alerts — do "
    "not invent extra metrics, files, or platforms. Respond with a SINGLE "
    "JSON object, and nothing else (no markdown fences, no prose around "
    "it), with exactly these keys:\n"
    '  "config_files": an array of objects, each with keys "path" (a '
    "workspace-relative path such as \"monitoring/prometheus.yml\") and "
    '"content" (the COMPLETE file text, newlines escaped inside the JSON '
    "string). Sensible filename examples: prometheus.yml, "
    "prometheus_alerts.yml, datadog.yaml, newrelic.yml.\n"
    '  "dashboard_url": leave this as the empty string "" — you must not '
    "pretend a dashboard was created."
)


def _workspace_listing(app_path: str) -> str:
    """Return a compact listing of the app directory, honest about its size."""
    try:
        p = tool_api.workspace_path(app_path)
    except ValueError as exc:
        raise SkillInputError(f"invalid app_path {app_path!r}: {exc}") from exc
    if not p.exists() or not p.is_dir():
        raise SkillInputError(
            f"app_path {app_path!r} is not a directory in the workspace "
            f"(resolved to {Path(p)})"
        )
    entries = sorted(x.name for x in p.iterdir())[:50]
    return ", ".join(entries) if entries else "(empty directory)"


def _normalise_config_file(item: Any) -> Dict[str, str]:
    """Map a raw model config-file entry to {path, content} with str types."""
    if isinstance(item, dict):
        return {
            "path": coerce_str(item.get("path")),
            "content": coerce_str(item.get("content")),
        }
    return {"path": "", "content": coerce_str(item)}


async def handle(input_data: dict, provider) -> dict:
    """Generate platform monitoring configs; returns file contents + no URL."""
    app_path = require(input_data, "app_path", str, "application directory")
    metrics = require(input_data, "metrics", list, "metrics to track")
    alerting = require(input_data, "alerting", dict, "alerting spec")
    platform = require(input_data, "platform", str, "observability platform")
    if not metrics:
        raise SkillInputError("metrics must be a non-empty list of strings")
    for m in metrics:
        if not isinstance(m, str):
            raise SkillInputError("each metric must be a string")
    if platform not in _PLATFORMS:
        raise SkillInputError(
            f"platform must be one of {sorted(_PLATFORMS)}, got {platform!r}"
        )

    listing = _workspace_listing(app_path)

    prompt = (
        f"Application workspace path: {app_path}\n"
        f"Real top-level directory listing of that app: {listing}\n"
        f"Platform: {platform}\n\n"
        f"METRICS TO TRACK (real, supplied by the caller): {json.dumps(metrics)}\n\n"
        f"ALERTING SPEC (real, supplied by the caller): {json.dumps(alerting)}\n\n"
        f"Generate {platform} monitoring config files that instrument exactly "
        "the metrics above and encode exactly the alerting rules above.\n\n"
        'Return a single JSON object with keys "config_files" (array of '
        '{"path": string, "content": string}) and "dashboard_url" (empty '
        "string)."
    )

    data: Dict[str, Any] = await ask_llm_json(provider, prompt, system=SYSTEM)

    # Normalise TYPES only — paths and contents come from the model's reply
    # about the real app; dashboard_url is honestly empty (none was created).
    config_files: List[Dict[str, str]] = [
        cf
        for cf in (_normalise_config_file(x) for x in as_list(data.get("config_files")))
        if cf["path"] or cf["content"]
    ]
    return {
        "config_files": config_files,
        "dashboard_url": "",
    }
